### ISSUE TITLE
How to open a QLC+ project and let it start automatically in this image?

### ISSUE THREAD

**Issue by laustock** [scotttag/qlcplus-docker#1]
I am trying to use this docker image to open up a QLC+ program and then have it automatically launch the program. So I want to have the same functionality, so I would do this using the cli commands in a terminal.

Now my questions are:
Does this work with this image and if so, how do I get this to work?

**Comment by scotttag** [comment]
Thanks for reporting! I've added this as environment variables in commit #976c133 so you can define them at runtime or in your docker compose, I need to add some docs, this has just been a little personal project

Environment variables added:
WORKSPACE_FILE (default empty - set to your workspace file to open this on start)
OPERATE_MODE (default off - set to true to start in operate mode)

Also added:
QLC_WEB_SERVER (default off - set to true if you want to enable QLCs built-in webserver on port 9999)

**Comment by laustock** [comment]
Hey Scott, thank you for your response and for adding the requested feat., but because I was not sure if you will answer I began an own image and was successful. But be sure I will also check the feat you added for me!! :)
